opt_in_rules:
  - legacy_random
  - private_action
  - private_outlet
  - unneeded_parentheses_in_closure_argument
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces


excluded:
  - Kadai7/AppDelegate.swift
  - Kadai7/SceneDelegate.swift


line_length:
  warning: 300
  error: 500
